name: "MalayaWSL Build"

on:
  #push:
    #branches: [ main ]
    # Trigger only when Makefile is changed
    #paths: ['Makefile']
  workflow_dispatch:
  #schedule:
    # Trigger every Saturday at 11:59 UTC
    #- cron: "59 11 * * sat"

jobs:
  build:
    runs-on: ubuntu-22.04
    # Skip build with [ci skip] in commit
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'main'
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - run: mkdir -p release
      - name: install dependencies
        run: sudo apt install -y arch-install-scripts curl jq libarchive-tools make patch podman podman-docker tar unzip wget xz-utils
      - name: build package
        run: |
             wget -O Makefile https://raw.githubusercontent.com/changrui/ManjaroWSL/main/Makefile
             patch Makefile < manjaro-docker.patch
             sed -i 's/docker/podman/g' Makefile
             sudo make
             sudo make clean
             mv Manjaro.zip release/Manjaro.zip
      - name: save release as artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 10
          name: Manjaro.zip
          path: release
